FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache ca-certificates openssl && update-ca-certificates

COPY package*.json ./
RUN npm ci

EXPOSE 3000

CMD ["npx", "next", "dev", "--hostname", "0.0.0.0"]
