services:
  frontend:
    container_name: next-frontend
    build:
      context: .
      args:
        NEXT_PUBLIC_WP_API_URL: https://staged.rentasib.ru/wp-json/wp/v2
        NEXT_PUBLIC_WP_BASE_URL: https://staged.rentasib.ru
        NEXT_PUBLIC_SITE_URL: https://new.rentasib.ru
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env.production

