import type { Metadata } from 'next';
import type { Viewport } from 'next'
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/layout/Header';
import UpdatePathCookie from '@/components/common/Meta/UpdatePathCookie'
import { Footer } from '@/components/layout/Footer';

const lato = localFont({
	src: [
		{
			path: '../public/fonts/Lato-Light.ttf',
			weight: '300',
			style: 'normal',
		},
		{
			path: '../public/fonts/Lato-Regular.ttf',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../public/fonts/Lato-Medium.ttf',
			weight: '500',
			style: 'normal',
		},
		{
			path: '../public/fonts/Lato-Semibold.ttf',
			weight: '600',
			style: 'normal',
		},
		{
			path: '../public/fonts/Lato-Bold.ttf',
			weight: '700',
			style: 'normal',
		},
	],
	variable: '--font-lato',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export const viewport: Viewport = {
	initialScale: 1,
	maximumScale: 1,
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body
				className={`px-4 pt-[10px] pb-2 ${lato.variable} antialiased lg:max-w-[1280px] lg:mx-auto lg:px-[10px] lg:py-5`}
			>
				<UpdatePathCookie />
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
