import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Header } from '@/components/layout/Header';
import { Breadcrumbs } from '@/components/layout/Breadcrumbs';

const lato = localFont({
	src: [
		{
			path: '../public/fonts/Lato-Regular.ttf',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../public/fonts/Lato-Medium.ttf',
			weight: '500',
			style: 'normal',
		},
		{
			path: '../public/fonts/Lato-Semibold.ttf',
			weight: '600',
			style: 'normal',
		},
		{
			path: '../public/fonts/Lato-Bold.ttf',
			weight: '700',
			style: 'normal',
		},
	],
	variable: '--font-lato',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`px-4 py-2 ${lato.variable} antialiased lg:max-w-[1280px] lg:mx-auto lg:px-2 lg:py-5`}
			>
				<Header />
				<Breadcrumbs />

				{children}
			</body>
		</html>
	);
}
